### ISSUE TITLE
Add support for Dark Mode.

### ISSUE THREAD

**Issue by dmitshur** [shurcooL/Go-Package-Store#95]
It can look like this:

![image](https://user-images.githubusercontent.com/1924134/47958512-f3a25c00-dfa2-11e8-9c93-4f90fe514cdf.png)

Using https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme and roughly the following CSS.

<details><summary>Dark Mode CSS</summary><br>

```CSS
body {
	background-color: rgb(30, 30, 30);
	color: white;
}

a {
	color: hsla(210, 63%, 61%, 1);
}

header {
	background-color: hsla(209, 51%, 22%, 1);
}
header.update {
	background-color: hsla(209, 51%, 16%, 1);
}

.list-entry-header {
	background-color: hsla(0, 0%, 20%, 1);
	border-bottom: 1px solid hsla(0, 0%, 24%, 1);
}

.list-entry {
	border: 1px solid hsla(0, 0%, 26%, 1);
}
```

</details>
